# This file is automatically generated for code intellisense only.
# It does not reflect the actual implementation.

from __future__ import annotations
from collections.abc import Iterator

from . import core
from . import fusion

class StructuralConstraintInput(SimAttributeInput):
    """
    This class defines the methods and properties that pertain to the definition of a structural constraint.
    """
    def __init__(self):
        pass
    @staticmethod
    def cast(arg) -> StructuralConstraintInput:
        return StructuralConstraintInput()
    def setTargets(self, entities: list[core.Base]) -> bool:
        """
        Sets the targets, vertices/edges/faces of the model.
        entities : An array containing the entities to set the constraint on.
        Returns true if successful.
        """
        return bool()
    @property
    def type(self) -> ConstraintTypes:
        """
        Returns the type of the structural constraint.
        """
        return ConstraintTypes()
